name: instagram_clone
description: A minimal Instagram-like Flutter UI scaffold.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.7+3
  video_player: ^2.5.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/